require('./sharpen.test')
require('./levels.test')
require('./shadhi.test')
require('./defringe.test')
require('./exposure.test')
require('./basecurve.test')
require('./blend.test')
require('./clipping.test')
require('./flip.test')
require('./mask.test')

require('./errors.test')
